# Generated by Django 3.2 on 2021-04-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Stts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stts_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=200)),
                ('acc_dt_birthday', models.DateField()),
                ('acc_username', models.CharField(max_length=30)),
                ('acc_password', models.CharField(max_length=20)),
                ('acc_email', models.CharField(max_length=200)),
                ('acc_security_question_answer', models.CharField(max_length=200)),
                ('acc_password_was_reset', models.BooleanField(default=False)),
                ('security_question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.securityquestion')),
                ('stts_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.stts')),
            ],
        ),
    ]
