# Generated by Django 3.2 on 2021-04-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc',
            options={'verbose_name': 'Acc'},
        ),
        migrations.AlterModelOptions(
            name='securityquestion',
            options={'verbose_name': 'SecurityQuestion'},
        ),
        migrations.AlterModelOptions(
            name='stts',
            options={'verbose_name': 'Stts'},
        ),
    ]
