# Generated by Django 3.2 on 2021-04-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210419_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc',
            options={'verbose_name': 'Acc', 'verbose_name_plural': 'Acc'},
        ),
        migrations.AlterModelOptions(
            name='securityquestion',
            options={'verbose_name': 'SecurityQuestion', 'verbose_name_plural': 'SecurityQuestion'},
        ),
        migrations.AlterModelOptions(
            name='stts',
            options={'verbose_name': 'Stts', 'verbose_name_plural': 'Stts'},
        ),
    ]
