# Generated by Django 3.2 on 2021-05-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210419_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='acc_security_question_answer',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='security_question_id',
        ),
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
    ]
