# Generated by Django 3.2 on 2021-05-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20210510_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_to_name', models.CharField(max_length=200)),
                ('load_date', models.DateField()),
                ('loan_observation', models.CharField(max_length=200)),
                ('loan_return_date', models.DateField()),
                ('loan_estimated_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.acc')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loan',
            },
        ),
    ]
