# Generated by Django 3.2 on 2021-06-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_rename_load_date_loan_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
